runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://localhost:27017/dev
  APP_ID: 5LA5kojEziCljqw4vZ9iZGNRQXwaOJG0jmcQaLYY
  MASTER_KEY: 3DerL7gs4rHTdd2eaya6GjHGpP27tbtSpyqSlGMw
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  